name: Deploy Spring App with Docker to GCP Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build Spring Application with Gradle
        run: ./gradlew build -x test

      - name: Build Docker image
        run: |
          docker build -t my-spring-app .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '420.0.0'

      - name: Push Docker image to Google Container Registry
        run: |
          gcloud auth configure-docker
          docker tag my-spring-app gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-spring-app:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-spring-app:latest

      - name: Deploy to GCP Compute Engine
        run: |
          gcloud compute ssh --project ${{ secrets.GCP_PROJECT_ID }} --zone ${{ secrets.GCP_COMPUTE_ZONE }} ${{ secrets.GCP_INSTANCE_NAME }} --command "
            sudo docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-spring-app:latest &&
            sudo docker stop my-spring-app || true &&
            sudo docker rm my-spring-app || true &&
            sudo docker run -d --name my-spring-app -p 8080:8080 gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-spring-app:latest"
