name: Just Build with JDK 21

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Google Cloud 인증을 위한 권한

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 최신 버전 사용

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # 최신 버전 사용
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle # Gradle 캐싱 활성화로 빌드 속도 향상

      - name: Decode and write application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml

      - name: Decode and write application-prod.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PROD_YML }}" | base64 --decode > src/main/resources/application-prod.yml

      - name: Decode and write jwt.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_JWT }}" | base64 --decode > src/main/resources/jwt.yml

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test # 테스트 건너뛰고 빌드 (필요에 따라 제거)
